// Shared, professionally-styled Excel (.xlsx) report generator.
// Uses exceljs, imported dynamically so it is only loaded client-side.

export interface ReportTable {
    /** Section heading printed above the table (optional). */
    title?: string;
    headers: string[];
    /** Each row must have the same length as headers. */
    rows: (string | number | null | undefined)[][];
    /** Optional totals row appended + styled as a footer. */
    totalsRow?: (string | number | null | undefined)[];
    /** Numeric column indexes (0-based) that should be right-aligned / shown as numbers. */
    numericColumns?: number[];
    /** Autofilter (header dropdowns) toggle. Defaults true for data-heavy tables. */
    autofilter?: boolean;
}

export interface ReportOptions {
    fileName: string;
    title: string;
    subtitle?: string;
    /** Key/value pairs printed under the subtitle (e.g. Generated by, Scope, Period). */
    meta?: { label: string; value: string }[];
    casual?: { label: string; value: string | number }[];
    tables: ReportTable[];
    /** Color accent for headings, defaults to DepEd blue. */
    accent?: string;
    /** If true wraps clearMessage in a message sheet (unused, reserved). */
}

// DepEd brand palette
const BRAND = {
    blue: "0038A8",
    blueDark: "00296B",
    green: "008751",
    gold: "FCD116",
    red: "CE1126",
    slate: "64748B",
    light: "F1F5F9",
    medium: "E2E8F0",
    white: "FFFFFF",
    black: "1E293B",
    muted: "94A3B8",
};

function isNum(v: unknown): v is number {
    return typeof v === "number" && Number.isFinite(v);
}

function colLetter(index: number): string {
    let s = "";
    index++;
    while (index > 0) {
        const rem = (index - 1) % 26;
        s = String.fromCharCode(65 + rem) + s;
        index = Math.floor((index - 1) / 26);
    }
    return s;
}

function fmtDate(d: Date): string {
    return d.toLocaleDateString("en-PH", {
        year: "numeric",
        month: "long",
        day: "numeric",
    });
}

/** Prompt-free download of an ArrayBuffer as a Blob. */
export function triggerDownload(
    buffer: ArrayBuffer,
    fileName: string,
    type = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
): void {
    const blob = new Blob([buffer], { type });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = fileName;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
}

/**
 * Build a styled workbook and return its xlsx bytes as an ArrayBuffer.
 * All styling (title band, meta, bordered header with fill, zebra rows,
 * totals, autofilters, column widths, freeze panes) is applied here.
 */
export async function buildReportWorkbook(
    opts: ReportOptions,
): Promise<ArrayBuffer> {
    const ExcelJS = await import("exceljs");
    const wb = new ExcelJS.Workbook();
    wb.created = new Date();
    wb.modified = new Date();
    wb.creator = "CEDIMS";

    const wks = wb.addWorksheet("Report", {
        views: [{ showGridLines: false }],
        pageSetup: { orientation: "portrait", fitToPage: true, fitToWidth: 1 },
    });

    const accent = opts.accent || BRAND.blue;
    let row = 1;

    // ── Title band ───────────────────────────────────────────────
    wks.mergeCells(row, 1, row, 20);
    const titleCell = wks.getCell(row, 1);
    titleCell.value = (opts.title || "CEDIMS Report").toUpperCase();
    titleCell.font = { size: 18, bold: true, color: { argb: BRAND.white } };
    titleCell.fill = {
        type: "pattern",
        pattern: "solid",
        fgColor: { argb: accent },
    };
    titleCell.alignment = { vertical: "middle", horizontal: "left" };
    titleCell.border = {
        bottom: { style: "thick", color: { argb: BRAND.gold } },
    };
    wks.getRow(row).height = 34;
    row++;

    if (opts.subtitle) {
        wks.mergeCells(row, 1, row, 20);
        const sc = wks.getCell(row, 1);
        sc.value = opts.subtitle;
        sc.font = { size: 11, italic: true, color: { argb: BRAND.white } };
        sc.fill = {
            type: "pattern",
            pattern: "solid",
            fgColor: { argb: BRAND.blueDark },
        };
        sc.alignment = { vertical: "middle", horizontal: "left" };
        wks.getRow(row).height = 22;
        row++;
    }

    row++; // blank spacer

    // ── Meta block ───────────────────────────────────────────────
    const metaRows: { label: string; value: string }[] = [
        { label: "Generated On", value: fmtDate(new Date()) },
        ...(opts.meta || []),
    ];
    for (const m of metaRows) {
        const lc = wks.getCell(row, 1);
        lc.value = m.label;
        lc.font = { bold: true, color: { argb: BRAND.slate }, size: 10 };
        wks.mergeCells(row, 2, row, 6);
        const vc = wks.getCell(row, 2);
        vc.value = m.value;
        vc.font = { bold: true, color: { argb: BRAND.black }, size: 10 };
        row++;
    }

    row++; // spacer

    // ── Tables ───────────────────────────────────────────────────
    let hadTable = false;
    for (const table of opts.tables) {
        if (!table.headers || table.headers.length === 0) continue;
        if (table.rows.length === 0) continue;
        hadTable = true;

        if (table.title) {
            wks.mergeCells(row, 1, row, table.headers.length);
            const tc = wks.getCell(row, 1);
            tc.value = table.title.toUpperCase();
            tc.font = { size: 12, bold: true, color: { argb: accent } };
            tc.alignment = { vertical: "middle", horizontal: "left" };
            wks.getRow(row).height = 20;
            row++;
        }

        const headerRowNum = row;
        const firstDataRow = headerRowNum + 1;
        const lastDataRow = firstDataRow + table.rows.length - 1;
        const lastCol = table.headers.length;

        // Header row
        const headerRow = wks.getRow(headerRowNum);
        headerRow.height = 20;
        table.headers.forEach((h, ci) => {
            const cell = headerRow.getCell(ci + 1);
            cell.value = h;
            cell.font = { bold: true, color: { argb: BRAND.white }, size: 10 };
            cell.fill = {
                type: "pattern",
                pattern: "solid",
                fgColor: { argb: table.totalsRow ? accent : BRAND.blueDark },
            };
            cell.alignment = {
                vertical: "middle",
                horizontal: isNum(table.rows[0]?.[ci]) ? "right" : "left",
            };
            for (const side of ["top", "bottom", "left", "right"] as const) {
                cell.border = {
                    ...(cell.border || {}),
                    [side]: {
                        style: "thin",
                        color: { argb: BRAND.medium },
                    },
                };
            }
        });

        // Data rows with zebra striping + borders
        table.rows.forEach((r, ri) => {
            const excelRow = wks.getRow(firstDataRow + ri);
            const isAlternate = ri % 2 === 1;
            r.forEach((val, ci) => {
                const cell = excelRow.getCell(ci + 1);
                if (isNum(val)) {
                    cell.value = val;
                    cell.numFmt = table.numericColumns?.includes(ci)
                        ? "0.00"
                        : "0";
                } else if (val == null) {
                    cell.value = null;
                } else {
                    cell.value = String(val);
                }
                cell.font = { size: 10, color: { argb: BRAND.black } };
                if (isAlternate) {
                    cell.fill = {
                        type: "pattern",
                        pattern: "solid",
                        fgColor: { argb: BRAND.light },
                    };
                }
                cell.alignment = {
                    vertical: "middle",
                    horizontal:
                        isNum(val) ||
                        table.numericColumns?.includes(ci)
                            ? "right"
                            : "left",
                };
                for (const side of ["top", "bottom", "left", "right"] as const) {
                    cell.border = {
                        ...(cell.border || {}),
                        [side]: { style: "thin", color: { argb: BRAND.medium } },
                    };
                }
            });
        });

        // Totals / footer row
        let footerRowNum: number | null = null;
        if (table.totalsRow) {
            footerRowNum = lastDataRow + 1;
            const fr = wks.getRow(footerRowNum);
            table.totalsRow.forEach((val, ci) => {
                const cell = fr.getCell(ci + 1);
                if (isNum(val)) {
                    cell.value = val;
                    cell.numFmt = "0.00";
                } else {
                    cell.value = val == null ? null : String(val);
                }
                cell.fill = {
                    type: "pattern",
                    pattern: "solid",
                    fgColor: { argb: BRAND.gold },
                };
                cell.font = { bold: true, size: 10, color: { argb: BRAND.black } };
                for (const side of ["top", "bottom", "left", "right"] as const) {
                    cell.border = {
                        ...(cell.border || {}),
                        [side]: { style: "thin", color: { argb: BRAND.medium } },
                    };
                }
            });
        }

        // Autofilter + freeze header
        if (table.autofilter !== false && table.rows.length > 0) {
            const totalRows =
                footerRowNum != null ? footerRowNum : lastDataRow;
            wks.autoFilter = {
                from: { row: headerRowNum, column: 1 },
                to: { row: totalRows, column: lastCol },
            };
        }
        wks.views = [
            {
                state: "frozen",
                ySplit: footerRowNum != null ? firstDataRow : firstDataRow,
                activeCell: `${colLetter(1)}${firstDataRow}`,
                showGridLines: false,
            },
        ];

        // Column widths tuned to content
        table.headers.forEach((h, ci) => {
            const headerLen = h.length;
            let maxLen = headerLen;
            for (const r of table.rows) {
                const v = r[ci];
                const len =
                    v == null ? 0 : typeof v === "number" ? 8 : String(v).length;
                if (len > maxLen) maxLen = len;
            }
            if (table.totalsRow) {
                const tv = table.totalsRow[ci];
                const tlen = tv == null ? 0 : String(tv).length;
                if (tlen > maxLen) maxLen = tlen;
            }
            const width = Math.min(45, Math.max(13, maxLen + 3));
            wks.getColumn(ci + 1).width = width;
        });

        row = (footerRowNum ?? lastDataRow) + 2; // spacer before next table
    }

    if (!hadTable) {
        wks.mergeCells(2, 1, 4, 4);
        const c = wks.getCell(2, 1);
        c.value = "No data available to export.";
        c.font = { italic: true, color: { argb: BRAND.slate } };
    }

    // Print-ready: repeat header on each printed page
    wks.pageSetup.printArea = `A1:L${row}`;
    wks.pageSetup.margins = {
        left: 0.5,
        right: 0.5,
        top: 0.6,
        bottom: 0.6,
        header: 0.3,
        footer: 0.3,
    };
    wks.properties.outlineLevelCol = 0;

    const buffer = await wb.xlsx.writeBuffer();
    return buffer as ArrayBuffer;
}

/**
 * High-level helper: build a styled report workbook and immediately download it,
 * returning a humanized summary message for toast feedback.
 */
export async function exportStyledExcel(
    opts: ReportOptions,
): Promise<string> {
    const buffer = await buildReportWorkbook(opts);
    triggerDownload(buffer, opts.fileName);
    const totalRows = opts.tables.reduce(
        (acc, t) => acc + t.rows.length,
        0,
    );
    return `Exported ${totalRows} record${totalRows === 1 ? "" : "s"} as ${opts.fileName}`;
}