import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
const require = createRequire(import.meta.url);
const { chromium } = process.env.PLAYWRIGHT_MODULE ? require(process.env.PLAYWRIGHT_MODULE) : require('playwright');
const browser = await chromium.launch({ headless: true, channel: 'msedge' });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, acceptDownloads: true });
const errors = [];
page.on('pageerror', e => { errors.push(e.message); console.error(e.message); });
page.on('requestfailed', request => console.error('Request failed:', request.url(), request.failure()?.errorText));
const base = process.env.COMPLIANCE_TEST_URL || 'http://127.0.0.1:5175';
try {
    await page.goto(base + '/tests/compliance-ui.html', { waitUntil: 'networkidle' });
    console.log('Initial period:', await page.getByLabel('Term', { exact: true }).inputValue(), await page.getByLabel('Week', { exact: true }).inputValue());
    await page.getByText('Submission completion: 0%', { exact: true }).waitFor();
    assert.equal(await page.getByLabel('Term', { exact: true }).inputValue(), '3');
    assert.equal(await page.getByLabel('Week', { exact: true }).inputValue(), '1');
    await page.getByLabel('Term', { exact: true }).selectOption('2');
    await page.getByLabel('Search teachers', { exact: true }).fill('Teacher 01');
    await page.getByText('Submission completion: 6%', { exact: true }).waitFor();
    await page.getByRole('button', { name: 'Show files for checking for Teacher 01', exact: true }).click();
    await page.getByRole('cell', { name: 'Late, submitted', exact: true }).waitFor();
    await page.getByRole('link', { name: 'Review DLL' }).waitFor();
    await page.reload({ waitUntil: 'networkidle' });
    await page.getByRole('link', { name: 'Review DLL' }).waitFor();
    await page.getByLabel('Term', { exact: true }).selectOption('2');
    await page.setViewportSize({ width: 320, height: 844 });
    assert.ok(await page.locator('.table-scroll').evaluate(el => el.scrollWidth <= el.clientWidth));
    await page.screenshot({ path: '.svelte-kit/compliance-school-mobile.png', fullPage: true });
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.getByRole('button', { name: 'Back to teachers' }).click();
    assert.equal(await page.getByLabel('Search teachers', { exact: true }).inputValue(), 'Teacher 01');
    await page.getByLabel('Search teachers', { exact: true }).fill('');
    await page.getByLabel('Term', { exact: true }).selectOption('3');
    await page.getByLabel('Week', { exact: true }).selectOption('1');
    await page.getByRole('button', { name: 'Show overdue DLLs for Teacher 02', exact: true }).click();
    await page.getByRole('cell', { name: 'Missing', exact: true }).waitFor();
    await page.getByRole('button', { name: 'Back to teachers' }).click();
    await page.goto(base + '/tests/compliance-ui.html?role=district', { waitUntil: 'networkidle' });
    await page.getByLabel('Term', { exact: true }).selectOption('2');
    await page.getByLabel('Week', { exact: true }).selectOption('1');
    await page.getByRole('button', { name: 'View school' }).click();
    await page.getByRole('button', { name: 'Back to district' }).waitFor();
    await page.getByRole('button', { name: 'Back to district' }).click();
    await page.getByRole('button', { name: 'View school' }).waitFor();
    await page.screenshot({ path: '.svelte-kit/compliance-district.png', fullPage: true });
    for (const width of [320, 390, 768]) {
        await page.setViewportSize({ width, height: 844 });
        assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'No page overflow');
        if (width <= 700) assert.ok(await page.locator('.table-scroll').evaluate(el => el.scrollWidth <= el.clientWidth), 'No sideways scrolling in mobile records');
        await page.getByRole('button', { name: 'Show overdue DLLs for Sample Elementary School', exact: true }).click();
        await page.getByRole('cell', { name: 'Missing', exact: true }).first().waitFor();
        if (width <= 700) assert.ok(await page.locator('.table-scroll').evaluate(el => el.scrollWidth <= el.clientWidth));
        await page.getByRole('button', { name: 'Back to district' }).click();
    }
    await page.setViewportSize({ width: 390, height: 844 });
    await page.screenshot({ path: '.svelte-kit/compliance-mobile.png', fullPage: true });
    assert.deepEqual(errors, []);
    console.log('Passed: role separation, drill-down, back navigation, stable totals, term filters, export and mobile width.');
} finally { await browser.close(); }
