import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
const require = createRequire(import.meta.url);
const { chromium } = process.env.PLAYWRIGHT_MODULE ? require(process.env.PLAYWRIGHT_MODULE) : require('playwright');
const browser = await chromium.launch({ headless: true, channel: 'msedge' });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, acceptDownloads: true });
const errors = [];
page.on('pageerror', e => errors.push(e.message));
const base = process.env.COMPLIANCE_TEST_URL || 'http://127.0.0.1:5175';
try {
    await page.goto(base + '/tests/compliance-ui.html', { waitUntil: 'networkidle' });
    await page.getByText('Completion: 2%', { exact: true }).waitFor();
    assert.equal(await page.getByRole('button', { name: 'View school', exact: true }).count(), 0);
    await page.getByLabel('Term', { exact: true }).selectOption('2');
    await page.getByLabel('Search teachers', { exact: true }).fill('Teacher 01');
    await page.getByText('Completion: 6%', { exact: true }).waitFor();
    await page.getByRole('button', { name: 'View DLLs' }).click();
    await page.getByRole('cell', { name: 'Late, submitted', exact: true }).waitFor();
    await page.getByRole('button', { name: 'Back to teachers' }).click();
    await page.getByRole('button', { name: 'Missing DLLs', exact: true }).click();
    await page.getByRole('cell', { name: 'Missing', exact: true }).first().waitFor();
    const downloaded = page.waitForEvent('download');
    await page.getByRole('button', { name: 'Export period report' }).click();
    const download = await downloaded;
    const ExcelJS = require('exceljs');
    const book = new ExcelJS.Workbook(); await book.xlsx.readFile(await download.path());
    assert.equal(book.getWorksheet('Requirements').rowCount, 19);
    assert.equal(book.getWorksheet('Requirements').getCell('F2').value, 2);
    await page.goto(base + '/tests/compliance-ui.html?role=district', { waitUntil: 'networkidle' });
    await page.getByRole('button', { name: 'View school' }).click();
    await page.getByRole('button', { name: 'Back to district' }).waitFor();
    await page.getByRole('button', { name: 'Back to district' }).click();
    await page.getByRole('button', { name: 'View school' }).waitFor();
    await page.screenshot({ path: '.svelte-kit/compliance-district.png', fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.screenshot({ path: '.svelte-kit/compliance-mobile.png', fullPage: true });
    assert.deepEqual(errors, []);
    console.log('Passed: role separation, drill-down, back navigation, stable totals, term filters, export and mobile width.');
} finally { await browser.close(); }
