import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
const require = createRequire(import.meta.url);
const { chromium } = process.env.PLAYWRIGHT_MODULE ? require(process.env.PLAYWRIGHT_MODULE) : require('playwright');
const browser = await chromium.launch({ headless: true, channel: 'msedge' });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, acceptDownloads: true });
const errors = [];
page.on('pageerror', e => errors.push(e.message));
try {
    await page.goto(`${process.env.COMPLIANCE_TEST_URL || 'http://127.0.0.1:5175'}/tests/compliance-ui.html`, { waitUntil: 'domcontentloaded', timeout: 60000 });
    await page.getByText('Completion: 2%', { exact: true }).waitFor();
    await page.getByLabel('Term', { exact: true }).selectOption('2');
    await page.getByText('Completion: 6%', { exact: true }).waitFor();
    await page.getByLabel('Search teachers or schools').fill('Teacher 01');
    await page.getByText('Completion: 100%', { exact: true }).waitFor();
    await page.getByRole('button', { name: 'All requirements', exact: true }).click();
    await page.getByRole('cell', { name: 'Late, submitted', exact: true }).waitFor();
    await page.getByRole('cell', { name: 'Approved', exact: true }).waitFor();
    const downloadEvent = page.waitForEvent('download');
    await page.getByRole('button', { name: 'Export Excel' }).click();
    const download = await downloadEvent;
    const ExcelJS = require('exceljs');
    const book = new ExcelJS.Workbook(); await book.xlsx.readFile(await download.path());
    assert.equal(book.getWorksheet('Requirements').rowCount, 2);
    assert.equal(book.getWorksheet('Requirements').getCell('F2').value, 2);
    await page.getByLabel('Term', { exact: true }).selectOption('1');
    await page.getByRole('button', { name: 'Missing matrix', exact: true }).click();
    await page.getByRole('cell', { name: 'Missing', exact: true }).waitFor();
    await page.getByLabel('Search teachers or schools').fill('');
    await page.getByLabel('Term', { exact: true }).selectOption('all');
    await page.screenshot({ path: 'tests/compliance-desktop.png', fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    await page.screenshot({ path: 'tests/compliance-mobile.png', fullPage: true });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'Page must not overflow on mobile');
    await page.getByRole('button', { name: 'Teachers', exact: true }).click();
    await page.getByRole('button', { name: 'Next page' }).click();
    await page.getByText('Teacher 18', { exact: true }).waitFor();
    await page.getByLabel('Search teachers or schools').fill('No such teacher');
    await page.getByText('No results match these filters.').waitFor();
    assert.deepEqual(errors, []);
    console.log('Passed: term isolation, filters, review state, missing matrix, export contents, pagination, empty state and mobile width.');
} finally { await browser.close(); }
